services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "8089:9000"
      - "8083:80"
    volumes:
      - /docker-compose/php:/app

    networks:
      - minha-rede

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testdb"
    ports:
      - "3308:3306"
    volumes:
      - /docker-compose/mysql-C/:/var/lib/mysql
    networks:
      - minha-rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "8085:80"
    volumes:
      - /docker-compose/php/admin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
